"""new fields in user model

Revision ID: 66798c5d5234
Revises: 0344a00d99e5
Create Date: 2021-01-25 07:52:06.545073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66798c5d5234'
down_revision = '0344a00d99e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
